
#define HOTKEY_CODEMSG_TOGGLE_REMAPPING 985437341
#define HOTKEY_CODEMSG_ACTIVATE_ARTMODE 932595471


#define ATTEMPT_FAILED false
#define ATTEMPT_SUCCESS true


#define MIN_DISPLACEMENT_DRAG 200
#define MAX_DEVIATION_THRESHOLD 150
#define MAX_REMAPLESS_DISPLACEMENT 24
